# Generated by Django 4.2 on 2023-04-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_menu_menu_item_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="reservation_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="reservation_slot",
            field=models.SmallIntegerField(default=10),
        ),
    ]
