# Generated by Django 4.2 on 2023-04-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0003_booking_reservation_date_booking_reservation_slot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="guest_number",
            field=models.IntegerField(default=1),
        ),
    ]
